#!/bin/sh

[ -f /etc/sysconfig/mksd ] && . /etc/sysconfig/mksd

[ -z "$UPDATE_HOUR" ] && UPDATE_HOUR=2
DIV="$(echo "$(LC_ALL=C date "+%H % ${UPDATE_HOUR}")" | bc)"
[ "$DIV" = "0" ] || exit 0

[ -z "$UPDATE_MAIL_MESSAGES" ] && UPDATE_MAIL_MESSAGES="errors"
[ "$UPDATE_MAIL_MESSAGES" = "errors" ] && redirect="1>/dev/null"

umask 022
log=$(eval /usr/bin/mksupdate.sh get 2>&1 $redirect)
[ "$UPDATE_MAIL_MESSAGES" != "none" -a -n "$log" ] && echo "$log"
